### ISSUE TITLE
Learn tests not working

### ISSUE THREAD

**Issue by kdonovan2005** [learn-co-curriculum/js-hashes-readme#8]
All tests pass in the browser but when I run learn, no tests pass

**Comment by pletcher** [comment]
This happens because phantomjs doesn't yet support any ES6 features. I can't seem to find your fork, but make sure that you're only using features from ES5. I'll circle back and fix this lab soon.

**Comment by kdonovan2005** [comment]
Cool is there a work around I can use to run the learn tests in the
meantime? Or do I just need to suffer the red lights?

Thanks!
Kristin

**Comment by pletcher** [comment]
Pushed a fix. You'll need to update your learn gem (`gem update learn-co`) -- make sure `learn-test --version` returns at least `2.3.0` :)
